### ISSUE TITLE
Issue 5(Suggestion): Boss AI/Attack Pattern Only Targeting player one.

### ISSUE THREAD

**Issue by lawlbit** [David-Hobson/project-nebula#115]
In the boss fight only player one is targeted, thus as one person playing both characters the boss can be defeated by causing it to walk into the line of fire of player 2. I think there are three possible solutions to this. Either make the boss's targeting more varied or have the attacks be area of effect or have additional mobs in the boss room to act as obstacles.

**Comment by FrankYang1995** [comment]
bug has been fixed
