### ISSUE TITLE
Issue #6(Bug/Suggestion): Shooting Dead Angles

### ISSUE THREAD

**Issue by lawlbit** [David-Hobson/project-nebula#116]
The shooting in the game feels good in the areas that can be shot at.  However there are areas that that cant be shot at, as highlighted by the picture attached. I think it would improve the games feel if the bounds on the shooting angles were not there. ie. Player being able to shoot at full range of 360 degrees.

![image](https://user-images.githubusercontent.com/15020935/51053364-6af9fa80-15a7-11e9-8135-eaef552d2369.png)

**Comment by FrankYang1995** [comment]
that is our design. Players cannot shoot side ways.
