### ISSUE TITLE
Issue #10(Bug): No collision with Boss

### ISSUE THREAD

**Issue by lawlbit** [David-Hobson/project-nebula#121]
When in the final boss stage, the player is able to just run through the boss without taking damage. May become an issue later on but unsure currently. Might be a balance thing.
![image](https://user-images.githubusercontent.com/15020935/51054463-ed37ee00-15aa-11e9-9f58-89e699f31cf6.png)

**Comment by FrankYang1995** [comment]
just added trigger to the boss
