### ISSUE TITLE
ISSUE: Boss only targets player 1 and player 2 takes no damage when walking through boss while its tracking player 1

### ISSUE THREAD

**Issue by wildingelijah** [David-Hobson/project-nebula#136]
#### Context
The boss only targets player 1 while both players are alive and player 2 takes no damage whatsoever. 
#### Expected Output
Boss can target and attack both players. Both characters then take damage depending on who the boss attacks. 
#### Actual Output
Boss targets player 1 until player 1 dies. 
### Steps to Reproduce
1. Enter boss room with both players.
### Bug Appearance
This happens every time so my assumption is that currently the boss can only target one player at a time. Player 2 will literally take no damage whatsoever even when walking through boss (while player 1 is alive).
### System Configuration
Resolution: Full screen
OS: Windows
Controller Type: Xbox 360

**Comment by FrankYang1995** [comment]
It is a bug and fixed now
