### ISSUE TITLE
Bug: Start screen Gamepad controls unresponsive if you game goes out of focus.

### ISSUE THREAD

**Issue by Chaozs** [David-Hobson/project-nebula#143]
Testing on windowed mode. 
Where: in-game and in-menu.

What happens: When I click outside the game onto some other application with the mouse, the controls no longer work when I go back into the game with PS4 gamepad. (mouse still works).

Expected gamepad functionality to still work after going back into game.

**Comment by ButterJX** [comment]
The mouse will not be implemented in game, thus it's not possible to switch out onto other applications.
