### ISSUE TITLE
Issue #8: Boss freezes and stops moving when player is slightly out of range

### ISSUE THREAD

**Issue by NathanCoit** [David-Hobson/project-nebula#164]
Boss will stop attacking or moving if the player can leave a certain range.
The player can still shoot and see the boss.
https://gyazo.com/0ee21b327a4bcf1e73f3c09835dc0d07

**Comment by FrankYang1995** [comment]
The reason is the boss only attacks two players if they are closed to the boss. I have adjust the distance to fix the bug
