### ISSUE TITLE
[Damian] ISSUE #3: Enemies cannot do Continuous Damage on Player.

### ISSUE THREAD

**Issue by DamianAngelone** [David-Hobson/project-nebula#21]
**Description**
When slimes (and potentially all enemies) make contact with a Player, the Player will lose HP as expected. But as long as this Slime maintains contact with the player they will not lose anymore HP. It isn't until the Player and Slime break contact and touch again before another 10 HP is lost.

**Steps to Reproduce**
- Locate an enemy
- Walk into the enemy
- Maintain contact with them
- Note that your health does not decrease
- Break contact with the enemy
- Make contact with the enemy again
- Note that your health no decreases as expected (though, only once)

**Appearance of Bug**
This bug is present through the entire game and occurs with all enemies. 

**Suggested Solutions**
This bug is likely due to a Boolean value that isn't being reset until contact with the enemy is broken. I believe a fix for this is having a Player lose 'X'-amount of HP as long as they are touching a Slime at anytime. And to avoid the Player from dying immediately from this, you can grant them a 'Y'-second invincibility period after taking the damage.

**System Configuration**
- Game tested as windowed (1280 x 600)
- OS: Microsoft Windows 10 (Version 10.0.17134)
- Tested on Laptop: 8GB RAM, Intel Core i5-4210U, 1.70GHz 
- Controller: 2 PS4 controllers

**Comment by FrankYang1995** [comment]
continuous collision will make the game difficult
