### ISSUE TITLE
[Damian] ISSUE #8: Boss will not Target nor Attack Player 2

### ISSUE THREAD

**Issue by DamianAngelone** [David-Hobson/project-nebula#26]
**Description**
Even after Player 1 dies, the boss will return to its idle state.

**Steps to Reproduce**
- Collect all the keys and enter the boss room
- Purposely let Player 1 die (which is not hard, because Player 2 will not even be targeted)
- Note that the boss will return to its idle state, continuing to ignore Player 2

**Appearance of Bug**
This setup was recreated several times with the same output each time while facing the boss. A possible rendition of this bug can be seen when fighting regular slimes: enemies will ignore Player 2 until Player 1 dies. This may a linked issue, except the boss continues to ignore Player 2 even after Player 1 is eliminated.

**Suggested Solutions**
Have the enemies target both players fairly, providing precedence either based on player distance from enemy or remaining health.

**System Configuration**
- Game tested as windowed (1280 x 600)
- OS: Microsoft Windows 10 (Version 10.0.17134)
- Tested on Laptop: 8GB RAM, Intel Core i5-4210U, 1.70GHz 
- Controller: 2 PS4 controllers

**Comment by FrankYang1995** [comment]
this bug has been fixed
