### ISSUE TITLE
[Damian] SUGGESTION #9: Blue Highlight on "Start" Button is Confusing

### ISSUE THREAD

**Issue by DamianAngelone** [David-Hobson/project-nebula#27]
**Targeted Mechanic**
The blue highlight on the start button makes it look like the button is highlighted, even though one of the other 2 buttons may actually be in focus.

**Suggestion**
Remove the blue highlight from the start button, or changing it so whatever is in focus is blue instead.

**Significance**
This will remove confusion from the user, because they can potentially be confused as to what menu option is actually in focus. This fix will allow the menu to correctly elicit feedback to the user and become intuitive.

**System Configuration**
- Game tested as windowed (1280 x 600)
- OS: Microsoft Windows 10 (Version 10.0.17134)
- Tested on Laptop: 8GB RAM, Intel Core i5-4210U, 1.70GHz 
- Controller: 2 PS4 controllers

**Comment by ButterJX** [comment]
The blue highlight is set to met the space setting. When you navigate on the buttons, the highlight colour will be white.
