### ISSUE TITLE
ISSUE: Multiple menu options highlighted

### ISSUE THREAD

**Issue by SusanSuY** [David-Hobson/project-nebula#29]
### Context
I was testing this game on my PC, which has both the controllers and mouse as inputs. Initially, I used the mouse to open the game, and left the mouse hovering over the area where the "Start" option appeared. I then switched over to controller input, and attempted to select other menu options. Upon doing so, I noticed that both options were highlighted.

### Expected Output
Only the latest option which has been hovered over will be highlighted.

### Actual Output
If both mouse and controller are used and the mouse is hovering over an option while the controller attempts to select a different option, both options will be highlighted.

## Steps to Reproduce
1. Open the game to the main menu screen.
2. Use the mouse to hover over the "Start" option.
3. Use the controller to highlight the "Controls" option.
4. Notice that both "Start" and "Controls" options are highlighted.

## Appearance of Bug
This bug appears with any combination of menu options, as long as the two menu options are different.

### Game Resolution
This was tested on 1280x720 resolution in windowed mode.

### System Specifications
- **OS:** Windows 10 Education (Version 1809, OS build 17763.316) 64-bit
- **Processor:** Intel i5-3230M @ 2.60GHz
- **RAM:** 8GB
- **Controller type:** Mouse and Sony Dualshock 3 controller

**Comment by ButterJX** [comment]
Mouse will not be implemented in our game, as it is a game with controller. The highlight issue will not occur when there is only one input method.
