### ISSUE TITLE
ISSUE #7: boss HP bar covers centre screen

### ISSUE THREAD

**Issue by JohnnyEndrizzi** [David-Hobson/project-nebula#45]
Boss hp bar covers the centre screen. It behaves as expected and is fixed in place.  

This can be fixed by anchoring the location of the bar to the a location independent of resolution.

Resolution tested on screen default of 1600 x 1024

https://i.imgur.com/ictsO2Z.png

**Comment by ButterJX** [comment]
Fixed.
