### ISSUE TITLE
ISSUE #8: Boss breaks when player 1 dies

### ISSUE THREAD

**Issue by JohnnyEndrizzi** [David-Hobson/project-nebula#46]
See attached video for exact symptoms.
https://www.dropbox.com/s/mr76ybmq4a0ml9n/2019-01-06_22-21-07.mp4?dl=0

Steps to recreate:
1. get into boss room
2. get boss attention
3. return to room spawn
(boss and players are now locked in the hallway)
4. if player 1 dies, the boss script breaks
(boss unresponsive, boss attacks frozen and harmless, if 'shield' is on, it stays on)
(if boss hp hits 0, it goes negative, game ends once the player walks into the boss)

This is most likely due to a crashed or terminated script due to a reliance on player 1 which assumes the game/script ends when the player dies. It should check for player 2 before terminating.

**Comment by FrankYang1995** [comment]
this bug has been fixed
