### ISSUE TITLE
Suggestion: Add color/icon representative of each player to their HP bar / player info.

### ISSUE THREAD

**Issue by nicolaikozel** [David-Hobson/project-nebula#51]
It is a bit confusing to know which HP bar / player info belongs to what character. This could be improved by having each character represented by a color+icon and this be displayed somehow on their character and their character info (hp, etc.). This eliminates any guesswork by the player. This will become more crucial if things like status effects, buffs, items, etc are added later. The players should easily be able to tell what is affecting them AND affecting their partner so they can react accordingly.

**Comment by ButterJX** [comment]
Fixed.
