### ISSUE TITLE
Issue: Boss clips through wall and is un-killable.

### ISSUE THREAD

**Issue by nicolaikozel** [David-Hobson/project-nebula#58]
![image](https://user-images.githubusercontent.com/22007300/50913461-6a742f00-1402-11e9-986c-b89dab82e36c.png)

If the player runs back to the entrance to the dungeon, the boss will follow them but will clip through the wall and be out of bounds. This traps the player and the boss is unkillable because the bullets don't travel through walls but the boss's attacks do.

**Comment by FrankYang1995** [comment]
Added collider to the boss to fix the bug
