### ISSUE TITLE
Issue: Monsters and Crystals not targeting Red player

### ISSUE THREAD

**Issue by sma7560** [David-Hobson/project-nebula#75]
Enemies are unresponsive when Red player goes up to a monster and runs circles around it. Can still be damaged and die from Red Player. Could be related to #74 .

**Comment by sma7560** [comment]
Also applies to dropped crystals

**Comment by sma7560** [comment]
Likely related to #26

**Comment by FrankYang1995** [comment]
it was a bug. it has been fixed
